# Generated by Django 2.1.4 on 2018-12-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='images/users/'),
        ),
    ]
