# Generated by Django 2.1.4 on 2018-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0002_auto_20181218_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='floor',
        ),
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
