# Generated by Django 2.1.4 on 2018-12-18 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0003_auto_20181218_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCleaning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cleaning_time', models.DateField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Rooms')),
            ],
        ),
    ]
