# Generated by Django 2.1.4 on 2018-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0003_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='is_balcony',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='is_smoke',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
