# Generated by Django 2.1.4 on 2018-12-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0004_auto_20181209_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='is_balcony',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='is_smoke',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='number_of_beds',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
