# Generated by Django 2.1.4 on 2018-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0005_auto_20181209_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='is_balcony',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_balcony',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
