# Generated by Django 2.1.4 on 2018-12-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0006_auto_20181211_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='is_smoke',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='number_of_beds',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='is_balcony',
            field=models.BooleanField(default=False),
        ),
    ]
