# Generated by Django 2.1.4 on 2018-12-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0007_auto_20181211_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='easy.Rooms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
