# Generated by Django 2.1.4 on 2018-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0008_auto_20181212_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_type',
        ),
        migrations.AddField(
            model_name='rooms',
            name='child_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='double_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='is_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='is_smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='single_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='square_meter',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
