# Generated by Django 2.1.4 on 2018-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0009_auto_20181212_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='is_balcony',
            new_name='has_air_cond',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='is_smoke',
            new_name='has_balcony',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='view',
            new_name='has_tv',
        ),
        migrations.AddField(
            model_name='rooms',
            name='has_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='smokable',
            field=models.BooleanField(default=False),
        ),
    ]
