# Generated by Django 2.1.4 on 2018-12-13 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0011_auto_20181213_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservicebooking',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='easy.RoomService'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='photo',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/items/'),
        ),
        migrations.AlterField(
            model_name='roomservicebooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.Booking'),
        ),
    ]
