# Generated by Django 2.1.4 on 2018-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0012_auto_20181213_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
