# Generated by Django 2.1.4 on 2018-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0013_auto_20181213_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='photo',
        ),
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(null=True, upload_to='images/items/'),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='image',
            field=models.ImageField(null=True, upload_to='images/items/'),
        ),
    ]
