# Generated by Django 2.1.4 on 2018-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0014_auto_20181213_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='image',
            field=models.ImageField(null=True, upload_to='images/rooms/'),
        ),
    ]
