# Generated by Django 2.1.4 on 2018-12-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0015_auto_20181213_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='guests',
            name='image',
            field=models.ImageField(null=True, upload_to='images/guests/'),
        ),
    ]
