# Generated by Django 2.1.4 on 2018-12-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0016_auto_20181214_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
